#!/bin/bash

current_date_time=$(date +'%Y-%m-%d %H:%M:%S')
local_machine_name=$(hostname)

csv_file="/home/george/.gitautosync"

while IFS=, read -r path label; do
	cd "$path"

	if [ -n "$(git status --porcelain)" ]; then
		git add .
		git commit -m "$current_date_time on $local_machine_name"
		git push
		notify-send -i face-smile "Git Sync OK" "Sucessfully pushed $label"
	else
		if ! git pull --rebase; then
			notify-send -i face-sad "Git Sync CONFLICT" "There was a conflict when pulling changes for $label"
		else
			notify-send -i face-smile "Git Sync OK" "Sucessfully pulled $label"
		fi
	fi
done <"$csv_file"
